import type { Metadata } from 'next'
import localFont from 'next/font/local'
import AuthProvider from './context/AuthProvider'
import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import './assets/css/globals.css'
import 'leaflet/dist/leaflet.css';

const myFont = localFont({
  src: './lib/font/Mitr/Mitr-Light.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Plantiew',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <MantineProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
