import type { Metadata } from 'next'
import localFont from 'next/font/local'
import AuthProvider from './context/AuthProvider'
import './assets/css/globals.css'

const myFont = localFont({
  src: './lib/font/Mitr/Mitr-Light.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Plantiew',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
          <script async
            src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&loading=async&libraries=places&callback=initMap">
          </script>
      </head>

      <body className={myFont.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
